/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package battleship.client;

import com.neovisionaries.ws.client.WebSocket;
import com.neovisionaries.ws.client.WebSocketFactory;

import java.io.IOException;

public class Battleship {
    
    WebSocket ws;

    public boolean someLibraryMethod() {
        return true;
    }

    public void createWebsocketConnection() throws IOException {
        ws = new WebSocketFactory().createSocket("wss://simfony.tech/mitty/websocket");
    }

    public WebSocket getWebSocket() {
        return ws;
    }
}