/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package battleship.client;

import java.net.URI;

import org.java_websocket.client.WebSocketClient;
import org.java_websocket.handshake.ServerHandshake;

public class Client extends WebSocketClient {

    Battleship battleship;

    public boolean someLibraryMethod() { // poggers name
        return true;
    }

    public Client(URI serverURI, Battleship battleship) {
        super(serverURI);
        this.battleship = battleship;
    }

    @Override
    public void onOpen(ServerHandshake handshakedata) {
        System.out.println("Connected");
    }

    @Override
    public void onMessage(String message) {
        try {
            battleship.recievedText(message);
        } catch (BattleshipParsingException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onClose(int code, String reason, boolean remote) {
        // TODO Auto-generated method stub

    }

    @Override
    public void onError(Exception ex) {
        // TODO Auto-generated method stub

    }
}