/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import battleship.client.Battleship;

public class App extends Battleship {
    public App() throws Exception {
        super();
    }

    @Override
    public void recievedText(String msg) {
        System.out.println(msg);
    }

    public static void main(String[] args) throws Exception {
        App app = new App();
        
        app.sendText("{\"option\": \"dio\"}");
    }
}