/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import battleship.client.Library;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Library test = new Library();

        if (test.someLibraryMethod()) {
            System.out.println("hiiiii");
        }
    }
}
