/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import battleship.client.Battleship;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());

        Battleship test = new Battleship();
        test.sendText("Bye");
    }
}
